{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/datacapturing\/status\/error(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing\/Status\/error(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The status returned if an asynchronous callback has finished with an error. Details about the error are available via the "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" parameter."}],"kind":"symbol","metadata":{"role":"symbol","title":"Status.error(_:)","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"case","externalID":"s:13DataCapturing6StatusO5erroryACs5Error_pcACmF","modules":[{"name":"DataCapturing"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing","doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing\/Status"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use Swift 5 Result or Swift 5.5 async\/await"}]}],"references":{"doc://org.cocoapods.DataCapturing/documentation/DataCapturing":{"role":"collection","title":"DataCapturing","abstract":[],"identifier":"doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing"},"doc://org.cocoapods.DataCapturing/documentation/DataCapturing/Status":{"deprecated":true,"role":"symbol","title":"Status","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"abstract":[{"type":"text","text":"The status returned by asynchronous callback handlers."}],"identifier":"doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing\/Status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Status"}],"url":"\/documentation\/datacapturing\/status"},"doc://org.cocoapods.DataCapturing/documentation/DataCapturing/Status/error(_:)":{"role":"symbol","title":"Status.error(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The status returned if an asynchronous callback has finished with an error. Details about the error are available via the "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" parameter."}],"identifier":"doc:\/\/org.cocoapods.DataCapturing\/documentation\/DataCapturing\/Status\/error(_:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/datacapturing\/status\/error(_:)"}}}