{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReadable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"cause: Another error, from system level, providing more detailed information."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/datacapturing\/filesupporterror\/notreadable(cause:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/notReadable(cause:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This error is thrown if the file system was not readable."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReadable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"FileSupportError.notReadable(cause:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:13DataCapturing16FileSupportErrorO11notReadableyACs0E0_p_tcACmF","modules":[{"name":"DataCapturing"}]},"hierarchy":{"paths":[["doc:\/\/DataCapturing\/documentation\/DataCapturing","doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError"]]},"references":{"doc://DataCapturing/documentation/DataCapturing":{"role":"collection","title":"DataCapturing","abstract":[],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing"},"doc://DataCapturing/documentation/DataCapturing/FileSupportError":{"role":"symbol","title":"FileSupportError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileSupportError"}],"abstract":[{"type":"text","text":"Errors created by the Cyface SDK associated with accessing the file system."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileSupportError"}],"url":"\/documentation\/datacapturing\/filesupporterror"},"doc://DataCapturing/documentation/DataCapturing/FileSupportError/notReadable(cause:)":{"role":"symbol","title":"FileSupportError.notReadable(cause:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReadable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This error is thrown if the file system was not readable."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/notReadable(cause:)","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing\/filesupporterror\/notreadable(cause:)"}}}